description: Generic IDE coding agent context (basic file operations and shell operations assumed to be covered; single project mode)
prompt: |
  You are running in an IDE assistant context where file operations, basic (line-based) edits and reads, 
  and shell commands are handled by your own, internal tools.
  
  If Serena's tools can be used to achieve your task, you should prioritize them.
  In particular, it is important that you avoid reading entire source code files unless it is strictly necessary!
  Instead, for exploring and reading code in a token-efficient manner, use Serena's overview and symbolic search tools.
  For non-code files or for reads where you don't know the symbol's name path, you can use the pattern search tool.

excluded_tools:
  - create_text_file
  - read_file
  - execute_shell_command
  - prepare_for_new_conversation

tool_description_overrides: {}

# whether to assume that Serena shall only work on a single project in this context (provided that a project is given
# when Serena is started).
# If set to true and a project is provided at startup, the set of tools is limited to those required by the project's
# concrete configuration, and other tools are excluded completely, allowing the set of tools to be minimal.
# Tools explicitly disabled by the project will not be available at all.
# The `activate_project` tool is always disabled in this case, as project switching cannot be allowed.
single_project: true
